// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});

// NEXT_APP_APP_NAME = "Asset management system"
// NEXT_APP_DESCRIPTION = "Asset management system"

// NEXT_APP_SERVER_URL = "http://localhost:3000"


// NEXTAUTH_SECRET = "2tF+z/QCyx/uYltmi+dtBUhCuQvNpsnbtollxQsmbz8="
// NEXTAUTH_URL= "http://localhost:3000/"
// NEXTAUTH_URL_INTERNAL = "http://localhost:3000/"

// DATABASE_URL="postgresql://neondb_owner:npg_1StYyUhe7Ixb@ep-wandering-surf-a1k798mm-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
